<?php

namespace App\Http\Resources\PluginUserResource\Pages;

use App\Http\Resources\PluginUserResource;
use Filament\Pages\Actions\Action;
use Filament\Resources\Pages\CreateRecord;

class CreatePluginUser extends CreateRecord
{
    protected static string $resource = PluginUserResource::class;

    protected function getTitle(): string
    {
        return 'Create New User'; // TODO: Change the autogenerated stub
    }



    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
}
